name: Deploy ci
on:
  push:
    branches:
      - "fix_ci_tests"
jobs:
  test:
    runs-on: ubuntu-latest
    env:
      ELASTIC_HOST: "localhost"
      ELASTIC_PASSWORD: "changeme"
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
    services:
      elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:6.3.2
        env:
          discovery.type: single-node
          ES_JAVA_OPTS: -Xms512m -Xmx512m
          ELASTIC_PASSWORD: changeme
          xpack.security.enabled: "false"
          http.cors.enabled: "true"
          http.cors.allow-origin: "*"
        ports:
          - 9200:9200
      rorapi:
        image: rorcommunity/ror-api:1.3.3
        env:
          ELASTIC_HOST: elasticsearch
          ELASTIC_PORT: 9200
          ELASTIC_PASSWORD: changeme
          ROR_BASE_URL: http://localhost
        ports:
          - 9292:80
          - 2222:22
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Cache dependency
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Set up Python environment
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"
      - name: Install requirements
        run: |
          docker --version
          rorapi=`docker ps --format "{{.Names}}" | grep ror`
          echo $rorapi
          docker exec $rorapi ls
