name: Deploy ci
on:
  push:
    branches:
      - "fix_ci_tests"
jobs:
  docker:
    runs-on: ubuntu-latest
    services:
      registry:
        image: registry:2
        ports:
          - 5000:5000
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          driver-opts: network=host
      - name: Build and push to local registry
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: localhost:5000/rorapi:${{ github.sha }}
  test:
    needs: docker
    runs-on: ubuntu-latest
    env:
      ELASTIC_HOST: "localhost"
      ELASTIC_PASSWORD: "changeme"
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
    services:
      elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:6.3.2
        env:
          discovery.type: single-node
          ES_JAVA_OPTS: -Xms512m -Xmx512m
          ELASTIC_PASSWORD: changeme
          xpack.security.enabled: "false"
          http.cors.enabled: "true"
          http.cors.allow-origin: "*"
        ports:
          - 9200:9200
      rorapi:
        image: localhost:5000/rorapi:${{ github.sha }}
        env:
          ELASTIC_HOST: elasticsearch
          ELASTIC_PORT: 9200
          ELASTIC_PASSWORD: changeme
          ROR_BASE_URL: http://localhost
        ports:
          - 9292:80
          - 2222:22
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Cache dependency
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Set up Python environment
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"
      - name: Run tests in docker container
        run: |
          rorapi=`docker ps --format "{{.Names}}" | grep ror`
          echo $rorapi
          docker exec $rorapi python manage.py setup
          docker exec $rorapi python manage.py test rorapi.tests
          docker exec $rorapi python manage.py test rorapi.tests_integration
          docker exec $rorapi python manage.py test rorapi.tests_functional
